"""add server default to page status

Revision ID: 78199abe35b9
Revises: 87d654f1278f
Create Date: 2026-02-17 15:16:19.205690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78199abe35b9'
down_revision: Union[str, Sequence[str], None] = '87d654f1278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='status'),
               existing_nullable=False)
    op.alter_column('pages', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='status'),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
