"""updated jobs attempt_count to server_default of 0

Revision ID: b70f3d682845
Revises: 78199abe35b9
Create Date: 2026-03-02 21:53:22.195177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70f3d682845'
down_revision: Union[str, Sequence[str], None] = '78199abe35b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
